const state={filter:'All',query:'',videos:[{title:'Midnight Stories',category:'Romantic',views:'128K',duration:'12:42',a:'#7d2f8d',b:'#32153a'},{title:'Private Moments',category:'Couples',views:'94K',duration:'09:18',a:'#9a3154',b:'#3d1826'},{title:'After Hours',category:'Amateur',views:'81K',duration:'15:06',a:'#5f2d78',b:'#20132d'},{title:'Velvet Room',category:'Solo',views:'72K',duration:'07:55',a:'#a23c7c',b:'#3b1530'},{title:'Slow Evening',category:'Romantic',views:'66K',duration:'11:24',a:'#6f315f',b:'#271627'},{title:'Night Shift',category:'Roleplay',views:'53K',duration:'14:39',a:'#4d356f',b:'#181326'}]};
const cats=['All','Amateur','Couples','Solo','Romantic','Roleplay'];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2400)}
function renderChips(){const wrap=$('#filterChips');wrap.innerHTML='';cats.forEach(c=>{const b=document.createElement('button');b.className='chip'+(state.filter===c?' active':'');b.textContent=c;b.onclick=()=>{state.filter=c;renderChips();renderVideos()};wrap.appendChild(b)})}
function renderVideos(){const q=state.query.trim().toLowerCase();const rows=state.videos.filter(v=>(state.filter==='All'||v.category===state.filter)&&(!q||`${v.title} ${v.category}`.toLowerCase().includes(q)));const grid=$('#videoGrid');grid.innerHTML='';rows.forEach(v=>{const card=document.createElement('article');card.className='video-card';card.innerHTML=`<div class="thumb" style="--card-a:${v.a};--card-b:${v.b}"><div class="play-small">▶</div><span class="duration">${v.duration}</span></div><div class="video-info"><h3>${v.title}</h3><div class="meta"><span>${v.category}</span><span>${v.views} views</span></div></div>`;card.onclick=()=>toast('Demo card — connect approved media storage for playback.');grid.appendChild(card)});$('#emptyState').hidden=rows.length!==0}
function renderCategories(){const counts={};state.videos.forEach(v=>counts[v.category]=(counts[v.category]||0)+1);const wrap=$('#categoryGrid');wrap.innerHTML='';cats.filter(c=>c!=='All').forEach(c=>{const el=document.createElement('button');el.className='category-card';el.innerHTML=`<strong>${c}</strong><span>${counts[c]||0} demo videos</span>`;el.onclick=()=>{state.filter=c;renderChips();renderVideos();document.querySelector('#trending').scrollIntoView({behavior:'smooth'})};wrap.appendChild(el)})}
function getSubmissions(){try{return JSON.parse(localStorage.getItem('vs_submissions')||'[]')}catch{return[]}}
function saveSubmissions(rows){localStorage.setItem('vs_submissions',JSON.stringify(rows));renderModeration()}
function renderModeration(){const rows=getSubmissions();const tbody=$('#moderationTable');tbody.innerHTML='';if(!rows.length){tbody.innerHTML='<tr><td colspan="5" style="color:#ad9fba">No submissions yet. Use “Submit video” to add a demo item.</td></tr>';return}rows.forEach((r,i)=>{const tr=document.createElement('tr');const cls=r.status==='Approved'?'approved':r.status==='Rejected'?'rejected':'';tr.innerHTML=`<td><strong>${escapeHtml(r.title)}</strong></td><td>${escapeHtml(r.category)}</td><td>${new Date(r.createdAt).toLocaleString()}</td><td><span class="badge ${cls}">${r.status}</span></td><td><div class="row-actions"><button class="mini" data-act="approve" data-i="${i}">Approve</button><button class="mini" data-act="reject" data-i="${i}">Reject</button><button class="mini" data-act="delete" data-i="${i}">Delete</button></div></td>`;tbody.appendChild(tr)})}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openModal(id){const el=document.getElementById(id);if(el){el.hidden=false;document.body.classList.add('locked')}}function closeModals(){$$('.modal').forEach(m=>m.hidden=true);document.body.classList.remove('locked')}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.open)));$$('[data-close]').forEach(b=>b.addEventListener('click',closeModals));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});
$('#enterBtn').onclick=()=>{localStorage.setItem('vs_age_ok','1');$('#ageGate').hidden=true;document.body.classList.remove('locked')};$('#leaveBtn').onclick=()=>{location.href='about:blank'};if(localStorage.getItem('vs_age_ok')==='1'){$('#ageGate').hidden=true}else{document.body.classList.add('locked')}
$('#searchToggle').onclick=()=>{const p=$('#searchPanel');p.hidden=!p.hidden;if(!p.hidden)$('#searchInput').focus()};$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;renderVideos()});$('#clearSearch').onclick=()=>{state.query='';$('#searchInput').value='';renderVideos()};
$('#uploadForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const rows=getSubmissions();rows.unshift({title:fd.get('title'),category:fd.get('category'),videoUrl:fd.get('videoUrl'),description:fd.get('description'),status:'Pending',createdAt:new Date().toISOString()});saveSubmissions(rows);e.currentTarget.reset();closeModals();toast('Submission added to the moderation queue.')});
$('#moderationTable').addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b)return;const i=Number(b.dataset.i),rows=getSubmissions();if(!rows[i])return;if(b.dataset.act==='delete')rows.splice(i,1);if(b.dataset.act==='approve')rows[i].status='Approved';if(b.dataset.act==='reject')rows[i].status='Rejected';saveSubmissions(rows);toast('Moderation queue updated.')});
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.reset();closeModals();toast('Demo login complete — connect a backend for real accounts.')});$('#reportForm').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.reset();closeModals();toast('Report recorded in demo mode.')});
$('#year').textContent=new Date().getFullYear();renderChips();renderVideos();renderCategories();renderModeration();