const state={filter:'All',query:'',videos:[],user:null};
const cats=['All','Amateur','Couples','Solo','Romantic','Roleplay','Other'];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const token=()=>localStorage.getItem('vs_token');
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2800)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function api(path,options={}){const headers={...(options.headers||{})};if(options.body&&!(options.body instanceof FormData)&&!headers['Content-Type'])headers['Content-Type']='application/json';if(token())headers.Authorization=`Bearer ${token()}`;const res=await fetch(path,{...options,headers});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`);return data}
function openModal(id){const el=document.getElementById(id);if(el){el.hidden=false;document.body.classList.add('locked')}}
function closeModals(){$$('.modal').forEach(m=>m.hidden=true);document.body.classList.remove('locked')}
function requireLogin(){if(!state.user){closeModals();openModal('loginModal');toast('Log in before uploading.');return false}return true}
function renderChips(){const wrap=$('#filterChips');wrap.innerHTML='';cats.forEach(c=>{const b=document.createElement('button');b.className='chip'+(state.filter===c?' active':'');b.textContent=c;b.onclick=()=>{state.filter=c;renderChips();renderVideos()};wrap.appendChild(b)})}
function renderVideos(){const q=state.query.trim().toLowerCase();const rows=state.videos.filter(v=>(state.filter==='All'||v.category===state.filter)&&(!q||`${v.title} ${v.category}`.toLowerCase().includes(q)));const grid=$('#videoGrid');grid.innerHTML='';rows.forEach(v=>{const card=document.createElement('article');card.className='video-card';card.innerHTML=`<div class="thumb" style="--card-a:#7d2f8d;--card-b:#20132d"><div class="play-small">▶</div><span class="duration">Private</span></div><div class="video-info"><h3>${escapeHtml(v.title)}</h3><div class="meta"><span>${escapeHtml(v.category)}</span><span>Approved</span></div></div>`;card.onclick=()=>playVideo(v.id);grid.appendChild(card)});$('#emptyState').hidden=rows.length!==0}
function renderCategories(){const counts={};state.videos.forEach(v=>counts[v.category]=(counts[v.category]||0)+1);const wrap=$('#categoryGrid');wrap.innerHTML='';cats.filter(c=>c!=='All').forEach(c=>{const el=document.createElement('button');el.className='category-card';el.innerHTML=`<strong>${c}</strong><span>${counts[c]||0} approved videos</span>`;el.onclick=()=>{state.filter=c;renderChips();renderVideos();$('#trending').scrollIntoView({behavior:'smooth'})};wrap.appendChild(el)})}
async function loadVideos(){try{const data=await api('/api/videos');state.videos=data.videos||[]}catch(e){console.error(e);state.videos=[]}renderVideos();renderCategories()}
async function playVideo(id){try{const {url}=await api(`/api/videos/${encodeURIComponent(id)}/play`);window.open(url,'_blank','noopener')}catch(e){toast(e.message)}}
function updateAccountUI(){const logged=Boolean(state.user);$('#loginBtn').hidden=logged;$('#logoutBtn').hidden=!logged;$('#accountLabel').hidden=!logged;$('#accountLabel').textContent=logged?`${state.user.role==='admin'?'Admin · ':''}${state.user.email}`:'';$('#admin').hidden=state.user?.role!=='admin';if(state.user?.role==='admin')loadAdminSubmissions()}
async function restoreSession(){if(!token())return updateAccountUI();try{const {user}=await api('/api/me');state.user=user}catch{localStorage.removeItem('vs_token');state.user=null}updateAccountUI()}
async function loadAdminSubmissions(){if(state.user?.role!=='admin')return;const tbody=$('#moderationTable');tbody.innerHTML='<tr><td colspan="5">Loading…</td></tr>';try{const {submissions}=await api('/api/admin/submissions');tbody.innerHTML='';if(!submissions.length){tbody.innerHTML='<tr><td colspan="5">No submissions yet.</td></tr>';return}submissions.forEach(r=>{const tr=document.createElement('tr');const cls=r.status==='approved'?'approved':r.status==='rejected'?'rejected':'';tr.innerHTML=`<td><strong>${escapeHtml(r.title)}</strong><br><small>${escapeHtml(r.submitter)}</small></td><td>${escapeHtml(r.category)}</td><td>${new Date(r.created_at).toLocaleString()}</td><td><span class="badge ${cls}">${escapeHtml(r.status)}</span></td><td><div class="row-actions"><button class="mini" data-act="approve" data-id="${r.id}">Approve</button><button class="mini" data-act="reject" data-id="${r.id}">Reject</button><button class="mini" data-act="delete" data-id="${r.id}">Delete</button></div></td>`;tbody.appendChild(tr)})}catch(e){tbody.innerHTML=`<tr><td colspan="5">${escapeHtml(e.message)}</td></tr>`}}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.open==='uploadModal'&&!requireLogin())return;openModal(b.dataset.open)}));$$('[data-close]').forEach(b=>b.addEventListener('click',closeModals));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});
$('#enterBtn').onclick=()=>{localStorage.setItem('vs_age_ok','1');$('#ageGate').hidden=true;document.body.classList.remove('locked')};$('#leaveBtn').onclick=()=>{location.href='about:blank'};if(localStorage.getItem('vs_age_ok')==='1')$('#ageGate').hidden=true;else document.body.classList.add('locked');
$('#searchToggle').onclick=()=>{const p=$('#searchPanel');p.hidden=!p.hidden;if(!p.hidden)$('#searchInput').focus()};$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;renderVideos()});$('#clearSearch').onclick=()=>{state.query='';$('#searchInput').value='';renderVideos()};
$('#showRegister').onclick=()=>{closeModals();openModal('registerModal')};
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{const data=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});localStorage.setItem('vs_token',data.token);state.user=data.user;e.currentTarget.reset();closeModals();updateAccountUI();toast('Logged in.')}catch(err){toast(err.message)}});
$('#registerForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{const data=await api('/api/auth/register',{method:'POST',body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});localStorage.setItem('vs_token',data.token);state.user=data.user;e.currentTarget.reset();closeModals();updateAccountUI();toast('Account created.')}catch(err){toast(err.message)}});
$('#logoutBtn').onclick=()=>{localStorage.removeItem('vs_token');state.user=null;updateAccountUI();toast('Logged out.')};
$('#uploadForm').addEventListener('submit',async e=>{e.preventDefault();if(!requireLogin())return;const form=e.currentTarget,fd=new FormData(form),file=fd.get('video'),btn=$('#uploadSubmit');if(!(file instanceof File)||!file.size)return toast('Choose a video file.');btn.disabled=true;const original=btn.textContent;try{btn.textContent='Preparing upload…';const signed=await api('/api/uploads/presign',{method:'POST',body:JSON.stringify({contentType:file.type,size:file.size})});btn.textContent='Uploading video…';const upload=await fetch(signed.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type,'Content-Length':String(file.size)},body:file});if(!upload.ok)throw new Error('Video upload failed.');btn.textContent='Creating submission…';await api('/api/submissions',{method:'POST',body:JSON.stringify({title:fd.get('title'),category:fd.get('category'),description:fd.get('description'),objectKey:signed.objectKey,adultVerified:fd.get('adult')==='on',consentConfirmed:fd.get('consent')==='on',rightsConfirmed:fd.get('rights')==='on'})});form.reset();closeModals();if(state.user?.role==='admin')loadAdminSubmissions();toast('Uploaded successfully and sent for moderation.')}catch(err){toast(err.message)}finally{btn.disabled=false;btn.textContent=original}});
$('#moderationTable').addEventListener('click',async e=>{const b=e.target.closest('[data-act]');if(!b)return;const id=b.dataset.id,act=b.dataset.act;try{if(act==='delete'){if(!confirm('Delete this submission and its stored video?'))return;await api(`/api/admin/submissions/${id}`,{method:'DELETE'})}else{let rejectionReason='';if(act==='reject')rejectionReason=prompt('Reason for rejection:')||'';await api(`/api/admin/submissions/${id}`,{method:'PATCH',body:JSON.stringify({status:act==='approve'?'approved':'rejected',rejectionReason})})}await loadAdminSubmissions();await loadVideos();toast('Moderation updated.')}catch(err){toast(err.message)}});
$('#reportForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await api('/api/reports',{method:'POST',body:JSON.stringify({contentRef:fd.get('contentRef'),reason:fd.get('reason'),details:fd.get('details')})});e.currentTarget.reset();closeModals();toast('Report submitted.')}catch(err){toast(err.message)}});
$('#year').textContent=new Date().getFullYear();renderChips();await restoreSession();await loadVideos();
